### ISSUE TITLE
Should port `http` be explicitly added on `Deployment`

### ISSUE THREAD

**Issue by ignasi35** [lagom/shopping-cart-scala#11]
YAML file for `shopping-cart` only lists `management` in the `ports` section. Should `http` also be added?

https://github.com/lagom/shopping-cart-scala/blob/e30b41723922ed635a8c072ea138262147a69cea/deploy/shopping-cart.yaml#L53-L55

**Comment by TimMoore** [comment]
I don't think it makes much difference. The only reason to name ports in the deployment is if you want to refer to them by name somewhere else.

If `http` is added to the deployment, it could be used to declare the port in the service, rather than hardcoding 9000:

https://github.com/lagom/shopping-cart-scala/blob/e30b41723922ed635a8c072ea138262147a69cea/deploy/shopping-cart.yaml#L85-L88

The change would be:

```diff
-       targetPort: 9000
+       targetPort: http
```

Is that more clear, though? IMHO it's just another layer of indirection and wouldn't add much clarity.

**Comment by TimMoore** [comment]
The reason it's specified for `management` is that the `kubernetes-api` discovery mechanism (currently) requires querying the port by name, but this is under discussion in https://github.com/akka/akka-management/issues/464 and https://github.com/akka/akka-management/pull/477.

**Comment by jroper** [comment]
In #22, I left management there because it's also used by the health checks below, better to specify the port number once than twice.

**Comment by ignasi35** [comment]
I don't think there's anything we have to change, then. Thanks @TimMoore and @jroper
